version: "3.9"
services:
  fileshare:
    build: .
    image: zst:${tag}
    container_name: zkinot
    network_mode: bridge
    pull_policy: never

networks:
  default: 
    external: true
    name: bridge
